name: Fast Kotlin/Java Lint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  kotlin-java-lint:
    name: Kotlin/Java Compilation Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        cd modules/termux-core && npm ci && cd ../..

    - name: Install Expo CLI
      run: npm install -g @expo/cli

    - name: Prebuild Android project
      run: npx expo prebuild --platform android

    - name: Check Kotlin/Java compilation
      run: |
        cd android
        ./gradlew compileDebugKotlin compileDebugJavaWithJavac --no-daemon --stacktrace
      continue-on-error: false

    - name: Show compilation errors if any
      if: failure()
      run: |
        echo "=== Gradle Build Logs ==="
        find android -name "*.log" -exec cat {} \;
        echo "=== Kotlin Compilation Errors ==="
        find android -path "*/build/tmp/kotlin-classes/*" -name "*.txt" -exec cat {} \;