name: Nightly Builds

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Trigger build and release workflow
      uses: actions/github-script@v7
      with:
        script: |
          const result = await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'build-release.yml',
            ref: 'main',
            inputs: {
              release_type: 'nightly'
            }
          });
          
          console.log('Triggered nightly build workflow');
          return result;
          
    - name: Create nightly issue
      uses: actions/github-script@v7
      with:
        script: |
          const date = new Date().toISOString().split('T')[0];
          
          const body = `## 🌙 Nightly Build - ${date}
          
          Automatic nightly build has been triggered.
          
          **What's included:**
          - Latest changes from main branch
          - Debug and release APK variants
          - Automated testing results
          - Screenshot artifacts from E2E tests
          
          The build will be available as a release once completed.
          
          **Status:** In Progress ⏳
          
          [View Build Progress](https://github.com/${context.repo.owner}/${context.repo.repo}/actions)`;
          
          try {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🌙 Nightly Build ${date}`,
              body: body,
              labels: ['nightly-build', 'automated']
            });
          } catch (error) {
            console.log('Could not create issue:', error.message);
          }